name: Build and deploy mobile app

on:
  push:
    branches: [development, master, staging]
    paths: [**]  # Remove the dependency on packages/mobile path
  workflow_dispatch:
    inputs:
      region:
        description: Region to target with build (development, staging, or production)
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development
      skip_upload_to_app_store:
        description: If set, builds the app as an artifact but does not upload to the play store
        required: false
        type: boolean
        default: false
      skip_ios:
        description: Skips the iOS portion of the build
        required: false
        type: boolean
        default: false
      skip_android:
        description: Skips the Android portion of the build
        required: false
        type: boolean
        default: false
      deployment_type:
        description: Whether to submit the app to app stores, or deploy via codepush
        required: true
        type: choice
        options:
          - codepush
          - appstore
        default: appstore

jobs:
  build_ios:  # Renamed job to build_ios
    name: Build iOS app
    runs-on: macos-13
    if: ${{ !inputs.skip_ios }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'
      - uses: actions/checkout@v3

      # Rest of the steps remain the same...

      - name: 'Upload ipa to app store'
        uses: nick-fields/retry@v2
        if: steps.releasetype.outputs.RELEASE_TYPE == 'appstore'
        with:
          timeout_minutes: 10,
          max_attempts: 3,
          command: >
            xcrun altool 
            --upload-app
            --type ios
            --file ios/build/mePrism.ipa
            --apiKey "${{ secrets.APP_STORE_CONNECT_API_KEY }}"  # Replace placeholder
            --apiIssuer "${{ secrets.APPSTORE_API_ISSUER }}"  # Replace placeholder

# You can keep the build_android and release sections unchanged if you want them for reference or future use.
